import { EventEmitter } from 'events';
import type { IPty, IPtyForkOptions } from './types.js';
export declare class MockPty extends EventEmitter implements IPty {
    readonly pid: number;
    cols: number;
    rows: number;
    private _isDestroyed;
    _dataCallbacks: Array<(data: string) => void>;
    private _exitCallbacks;
    private _command;
    private _args;
    private _cwd;
    private _env;
    private _inputBuffer;
    private _currentInput;
    private _isProcessing;
    private _outputBuffer;
    private _history;
    constructor(command: string, args: string[], options: IPtyForkOptions);
    private _simulateStartup;
    private _writeOutput;
    private _flushOutput;
    private _writePrompt;
    private _handleCommandExecution;
    private _processInputData;
    private _processSingleCharacter;
    private _handleEnter;
    private _handleBackspace;
    private _handleCtrlC;
    private _handleCtrlD;
    private _handleTab;
    private _handlePrintableChar;
    onData(callback: (data: string) => void): void;
    onExit(callback: (code: number, signal?: number) => void): void;
    write(data: string): void;
    resize(cols: number, rows: number): void;
    kill(signal?: string): void;
    destroy(code?: number, signal?: number): void;
    getCurrentInput(): string;
    isDestroyed(): boolean;
    getHistory(): string[];
}
